<a href="https://colab.research.google.com/github/Abdullah723669-cmk/00_pytorch-mamun/blob/mamunBranch/00_pytorch_mamun.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

2.9.0+cu126
True
Tesla T4


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [34]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [41]:
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.3180, 0.1155, 0.5888, 0.0095],
         [0.7127, 0.7404, 0.7109, 0.1296],
         [0.0557, 0.4438, 0.5992, 0.3967]],

        [[0.1603, 0.2990, 0.6999, 0.3875],
         [0.9158, 0.4420, 0.5066, 0.0527],
         [0.5092, 0.3844, 0.8912, 0.7892]]])

In [40]:
random_tensor.ndim

3

In [42]:
random_tensor.shape

torch.Size([2, 3, 4])

In [43]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)